name: 'Get Repo Name'
description: 'Gets the repository name that was added to the open-repositories.txt file.'
outputs:
  repo-name:
    value: ${{ steps.get-repo-name.outputs.new_repo }}
    description: "The name of the repository that was added."

runs:
  using: 'composite'
  steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get repo name
        id: get-repo-name
        run: |
          NEW_REPO=$(git diff origin/master...HEAD open-repositories.txt | grep "+" | tail -n 1 | sed 's/+//')
          echo "new_repo=$NEW_REPO" >> $GITHUB_OUTPUT
        shell: bash
