name: 'Get Repo Name'
description: 'Gets the repository name that was added to the open-repositories.txt file.'
outputs:
  repo-name:
    value: ${{ steps.get-repo-name.outputs.new_repo }}
    description: "Boolean if the repository accepts external contributions."

runs:
  using: 'composite'
  steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get repo name
        id: get-repo-name
        run: |
          git fetch origin master:rgefs/remotes/origin/master
          NEW_REPO=$(git diff origin/master...HEAD open-repositories.txt | grep "+" | tail -n 1 | sed 's/+//')
          echo $NEW_REPO
          echo "new_repo=$NEW_REPO"
          echo "new_repo=$NEW_REPO" >> $GITHUB_OUTPUT
        shell: bash

      - name: debug
        run: |
          echo ${{join(steps.get-repo-name.outputs.*, '\n')}}
          echo ${{ steps.get-repo-name.ouptuts.new_repo }}
        shell: bash