name: 'Get Repo Name'
description: 'Gets the repository name that was added to the open-repositories.txt file.'
outputs:
  repo-name:
    value: ${{ steps.get-repo-name.outputs.new_repo }}
    description: "The name of the repository that was added."
  new_repo_added:
    value: ${{ steps.get-repo-name.outputs.new_repo_added }}
    description: "Boolean if a new repo was added."

runs:
  using: 'composite'
  steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get repo name
        id: get-repo-name
        run: |
          set +e # curl exists with the code 1 when nothing found. This is not an error here, it just means no new repositories added.
          NEW_REPO=$(curl --silent --retry 5 https://raw.githubusercontent.com/dfinity/repositories-open-to-contributions/master/open-repositories.txt | grep -vFxf- open-repositories.txt)
          NEW_REPO=$(echo "$NEW_REPO" | sed 's/#.*//')
          E=$?
          if [ "$E" -gt 1 ]; then
            echo "curl exited with the code $E" >&2
            exit "$E"
          fi
          set -euo pipefail
          if [ -z "$NEW_REPO" ]; then
            echo "No repository added."
            exit 0
          fi
          REPO_COUNT=$(echo "$NEW_REPO" | wc -l)
          if (( REPO_COUNT > 1 )); then
            echo "Only one repository can be added at a time. Please create separate PRs."
            exit 1
          elif (( REPO_COUNT = 1 )); then
            echo "new_repo=$NEW_REPO" >> $GITHUB_OUTPUT
            echo "new_repo_added=True" >> $GITHUB_OUTPUT
          fi
        shell: bash
