#!/bin/bash

set -euo pipefail

# Integration test to ensure CLA closes PR for an external contributor

# set git credentials
git config user.name dfinity
git config user.email dfinity@dfinity.org

# get updates for forked repo
git fetch upstream
git checkout -b integration-test-$RUN_NUMBER
git merge upstream/$CURRENT_BRANCH integration-test-$RUN_NUMBER

# create new branch with commit
touch test.txt
git add test.txt
git commit --author="dfinity <dfinity@dfinity.org>" -m 'add empty file'

git remote -v

# create pull request
git push --set-upstream origin integration-test-$RUN_NUMBER

# does not work due to permissions, but keeping for reference
# gh pr create --repo dfinity/repositories-open-to-contributions --base $CURRENT_BRANCH --head dfinity-sandox/repositories-open-to-contributions:integration-test-$RUN_NUMBER --draft --title "Integration Test 3" --body "generated by integration test from branch $GITHUB_HEAD_REF"