name: 'Check External Contribution'
description: 'Check if the repository accepts external contributions.'
inputs:
  repo-name:
    description: "The name of the repository"
    default: ${{github.event.repository.name}}
    required: false
  github-token:
    description: 'Github token of the repository (automatically created by Github)'
    default: ${{ github.token }}
    required: false
outputs:
  accepts_contrib:
    value: ${{ steps.check-external-contrib.outputs.accepts_contrib }}
    description: "Boolean if the repository accepts external contributions."

runs:
  using: 'composite'
  steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install Dependencies
      run: pip install -r requirements.txt
      shell: bash
    - name: Check External Contribution
      id: check-external-contrib
      run: python .github/custom_python_actions/check_external_contrib.py
      shell: bash
      env:
        REPO: ${{ inputs.repo-name }}
        GH_TOKEN: ${{ inputs.github-token }}