# Workflow to check if a new repository has been added to list and is compliant

name: Check New Repo

on:
  pull_request:
    paths:
      - open-repositories.txt

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  check-repo-compliance:
    name: Check if repository is compliant
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get repo name
        uses: technote-space/get-diff-action@v4
        id: get-repo-name
        with:
          FILES: open-repositories.txt

      - name: Check if repository is compliant
        id:  check-compliance
        uses: ./.github/actions/check_compliance/
        with:
          repo-name: steps.get-repo-name.ouptuts.diff

      - name: Has README
        id: has-readme
        run: |
          if [ "${{ steps.check-compliance.outputs.has_readme }}" = "False" ]; then
            echo "Repo is not compliant - missing README"
            exit 1
          else
            exit 0
          fi

      - name: Has Codeowners file
        id: has-codeowners
        run: |
          if [ "${{ steps.check-compliance.outputs.has_codeowners }}" = "False" ]; then
            echo "Repo is not compliant - missing Codeowners file"
            exit 1
          else
            exit 0
          fi

      - name: Has License file
        id:  has-license
        run: |
          if [ "${{ steps.check-compliance.outputs.has_license }}" = "False" ]; then
            echo "Repo is not compliant - missing License file"
            exit 1
          else
             exit 0
          fi

      - name: Is branch protected
        id: is-branch-protected
        run: |
          if [ "${{ steps.check-compliance.outputs.is_branch_protected }}" = "False" ]; then
            echo "Repo is not compliant - is not branch protected"
            exit 1
          else
            exit 0
          fi
