# Workflow to run integration tests
# Checks that check_cla workflow works as expected

name: CLA Integration Tests

on:
  push:
    branches-ignore:
      - integration-test-3
    paths:
      - .github/custom_python_actions/check_cla_issue.py
      - .github/custom_python_actions/check_cla_pr.py
      - .github/tests/test_cla_issue.py
      - .github/tests/test_cla_pr.py
      - .github/workflows/check_cla.yml
      - .github/workflows/cla_integration_tests.yml
      - .github/integration_tests/external_contributor.sh
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  integration-test:
    name: CLA Integration Test
    runs-on: ubuntu-latest
    steps:
    - name: Extract branch name
        shell: bash
        run: echo "current_branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch
    - name: Checkout
      uses: actions/checkout@v3
      with:
        repository: 'dfinity-sandbox/repositories-open-to-contributions'
        ref: ${{ steps.extract_branch.outputs.current_branch }}

    - name: Integration Test External Contributor
      run: |
        ${GITHUB_WORKSPACE}/.github/integration_tests/external_contributor.sh
      env:
        GH_TOKEN: ${{ secrets.INTEGRATION_TEST_EXTERNAL_CONTRIBUTOR }}
