# Workflow to run integration tests
# Checks that check_new_repo workflow works as expected

name: Compliance Integration Tests

on:
  push:
    branches-ignore:
      - integration-test-1
      - integration-test-2
    paths:
      - .github/custom_python_actions/check_compliance.py
      - .github/custom_python_actions/check_external_contrib.py
      - .github/tests/test_compliance_checks.py
      - .github/tests/test_check_external_contrib.py
      - .github/workflows/check_existing_repo.yml
      - .github/workflows/check_new_repo.yml
      - .github/workflows/compliance_integration_tests.yml
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  compliance-integration-tests:
    name: Integration Test 1
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # - name: Integration Test Nonexistant repo
    #   run: |
    #     ${GITHUB_WORKSPACE}/.github/integration_tests/nonexistent_repo.sh
    #   env:
    #     GH_TOKEN: ${{ secrets.GH_TOKEN_RUN_WORKFLOW }}

    - name: Integration Test Compliant repo
      run: |
        ${GITHUB_WORKSPACE}/.github/integration_tests/compliant_repo.sh
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN_RUN_WORKFLOW }}
