# Workflow to run integration tests
# Checks that check_new_repo workflow works as expected

name: Integration Tests

on:
  pull_request:
    paths:
      - custom_python_actions/*
      - tests/*
      - .github/workflows/*
    # branches-ignore:
    #   - add-integration-tests
  merge_group:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  integration-test-1:
    name: Integration Test 1
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # - name: Check if Integration Test should be run
    #   run: |
    #     set -euo pipefail
    #     BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
    #     echo $BRANCH_NAME
    #     if [[ $BRANCH_NAME == '"integration-test-1"' ]]
    #     then
    #         RUN_INTEGRATION_TESTS="false"
    #     else
    #         RUN_INTEGRATION_TESTS="true"
    #     fi
    #     echo $RUN_INTEGRATION_TESTS
    #     echo "run_tests=$RUN_INTEGRATION_TESTS" >> $GITHUB_OUTPUT

    - name: Integration Test 1
      if: ${{ github.event.label.name == 'integration-test' }}
      run: |
        set -euo pipefail
  #      bash ${GITHUB_WORKSPACE}/.github/integration_tests/nonexistent_repo.sh
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN_RUN_WORKFLOW }}
