# Workflow to run linting and tests on python code

name: Python Workflow

on:
  pull_request:
    paths:
      - custom_python_actions/**
      - tests/**

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  python-test-and-lint:
    name: Test and Lint python code
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: pip install -r requirements-dev.txt

    - name: Run tests
      run: pytest
    
    - name: Run linter
      run: |
        mypy custom_python_actions/
        black custom_python_actions/
        flake8 custom_python_actions/