# Workflow to run linting and tests on python code

name: Python Workflow

on:
  pull_request:
    paths:
      - .github/custom_python_actions/**
      - .github/tests/**
  merge_group:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  python-test-and-lint:
    name: Test and Lint python code
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: pip install -r requirements.txt

    - name: Run tests
      run: pytest .github/
    
    - name: Run linter
      run: |
        mypy .github/custom_python_actions/
        black .github/custom_python_actions/
        flake8 .github/custom_python_actions/

    - name: Run all tests
      run: pytest --runslow .github/
