name: Sorting

on:
  pull_request:
    paths:
      - open-repositories.txt
  merge_group:

jobs:
  check:
    name: Check Sort
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check Sort
        uses: ./.github/actions/sorting
